#!/usr/bin/env bash
set -o errtrace
set -o errexit

echo "Enter the name of the Rails application:"
read app_name

RAILS_TEMPLATE="${RAILS_TEMPLATE:-https://raw.githubusercontent.com/RYLabs/ry-rails/master/template.rb}"

rails new "${app_name}" --skip-coffee -d postgresql --skip-test --template=${RAILS_TEMPLATE}
